service: sls-appsync-todo-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.TODO_TABLE}

plugins:
  - serverless-esbuild
  - serverless-appsync-plugin

custom:
  TODO_TABLE: todoTable
  esbuild:
    bundle: true
    minify: true

appSync:
  name: ${self:service}
  logging:
    level: ALL

  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      userPoolId: !Ref CognitoUserPool
      defaultAction: ALLOW

  dataSources:
    todos:
      type: AMAZON_DYNAMODB
      config:
        tableName: !Ref TodoTable

  resolvers:
    Query.listTodos:
      functions:
        - dataSource: todos
          code: resolvers/listTodos.js
    Query.getTodo:
      functions:
        - dataSource: todos
          code: resolvers/getTodo.js
    Mutation.addTodo:
      functions:
        - dataSource: todos
          code: resolvers/addTodo.js
    Mutation.updateTodo:
      functions:
        - dataSource: todos
          code: resolvers/updateTodo.js

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:custom.TODO_TABLE}-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: todoId
            AttributeType: S
        KeySchema:
          - AttributeName: todoId # partition key
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-user-pool-${self:provider.stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: ${self:service}-user-pool- client-${self:provider.stage}
        RefreshTokenValidity: 30
        GenerateSecret: false
  Outputs:
    UserPoolId:
      Value: !Ref CognitoUserPool
    UserPoolClientId:
      Value: !Ref CognitoUserPoolClient
